{{- $cert_manager := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.cert_manager -}}

{{- if eq $cert_manager "true" }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.jetstack.io
{{- end }}