apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  interval: 5m
  releaseName: cert-manager-crds
  targetNamespace: cert-manager
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: helm-umbrella-charts
        namespace: flux-system
      chart: resources/charts/cert-manager
  dependsOn:
    - name: cert-manager
      namespace: cert-manager