apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m
  path: "./infra/base/external-dns/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-umbrella-charts