apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 1m
  path: "./infra/base/cluster-autoscaler/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-umbrella-charts