{{- $cluster_autoscaler := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.cluster_autoscaler -}}

{{- if eq $cluster_autoscaler "true" }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: autoscaler
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/autoscaler
{{- end }}