apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
resources:
  - aws-load-balancer-controller/ks.yaml
  - cert-manager/ks.yaml
  - external-dns/ks.yaml
  - cluster-autoscaler/ks.yaml
  - weave-gitops/ks.yaml
