
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1m
  path: "./infra/base/weave-gitops/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-umbrella-charts