apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  path: "./infra/base/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-umbrella-charts