{{- $domain := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.domain -}}
{{- $cluster_name := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.cluster_name -}}
{{- $environment := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.environment -}}
{{- $repository := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.repository -}}
{{- $app_name := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.app_name -}}
{{- $custom_app := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.custom_app -}}

{{- if eq $custom_app "true" }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $app_name }}
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: {{ $app_name }}
        namespace: flux-system
  values: {
    domain: {{ $domain }},
    enviroment: {{ $environment }},
    cluster_name: {{ $cluster_name }}
  }
{{- end }}