{{- $external_dns := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.external_dns -}}

{{- if eq $external_dns "true" }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/external-dns/
