{{- $app_name := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.app_name -}}

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/base/demo-app/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ $app_name }}