{{- $region := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.region -}}
{{- $vpc_id := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.vpc_id -}}
{{- $cluster_name := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.cluster_name -}}


apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.7.1" 
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
  values:
    region: {{ $region }}
    vpcId: {{ $vpc_id }}
    clusterName: {{ $cluster_name }}
    enableCertManager: true
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
      
