{{- $eks_lb_role_arn := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.eks_lb_role_arn -}}
{{- $aws_load_balancer_controller := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.aws_load_balancer_controller -}}

{{- if eq $aws_load_balancer_controller "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: controller
  annotations:
    eks.amazonaws.com/role-arn: {{ $eks_lb_role_arn }}
    app.kubernetes.io/managed-by: "Helm"
    eks.amazonaws.com/sts-regional-endpoints: "true"
