{{- $cert_manager := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.cert_manager -}}

{{- if eq $cert_manager "true" }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: "v1.13.3" 
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    serviceAccount:
      create: false
      name: cert-manager
      extraArgs:
        - --issuer-ambient-credentials