{{- $eksCmRoleArn := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.eks_cm_role_arn -}}
{{- $cert_manager := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.cert_manager -}}

{{- if eq $cert_manager "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
  annotations:
    eks.amazonaws.com/role-arn: {{ $eksCmRoleArn }}
    app.kubernetes.io/managed-by: "Helm"
